### PR TITLE
Upgrade dependencies, drop Node.js 0.x

### PR DESCRIPTION
**Pull request by bajtos**
- Drop support for Node.js version older than 4.x
 - Upgrade LoopBack from 2.x to 3.x
 - Upgrade other dependencies to their latest versions

This commit fixes the following security vulnerability in lodash:

 - Prototype Pollution https://snyk.io/vuln/npm:lodash:20180130

### CODE REVIEW

**Review by jannyHou — APPROVED** [review]
👍

**Review by jannyHou — COMMENTED** [review]
@bajtos node 4 is failing due to 

> > eslint .
08:56:19 
08:56:20 
08:56:20 Oops! Something went wrong! :(
08:56:20 
08:56:20 ESLint: 4.18.1.
08:56:20 ESLint couldn't find the plugin "eslint-plugin-mocha". This can happen for a couple different reasons:
08:56:20 

Could you double check the new major version of eslint works fine with this repo?

**Comment by bajtos** [comment]
@jannyHou thanks. I checked CI error log. The `npm` version shipped in Node.js 4 uses a deep hierarchy in node_modules, therefore `eslint-plugin-mocha` must be explicitly listed as a dependency. I amended my commit, it should hopefully fix the problem.

**Comment by bajtos** [comment]
I made one more change - upgraded loopback-boot to 3.x

**Comment by bajtos** [comment]
`nsp@3` does not support Node.js 4.x, I have to downgrade to `nsp@2`. Hopefully that's the last change needed.

**Review by b-admike — APPROVED** [review]

**Pull request merged**
